# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapping/*mapping.xml
  type-aliases-package: com.rltx.**.entity
  global-config:
    banner: false
    db-config:
      id-type: 0
      field-strategy: 1
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true



server:
  port: 8091
spring:
  main:
    allow-bean-definition-overriding: true



data:
  org:
    light: true
  dept:
    light: true